# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyThesis', '0003_auto_20160625_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLangLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreignLang', models.CharField(max_length=10)),
                ('proficiency', models.IntegerField()),
                ('school', models.BooleanField(default=False)),
                ('schoolSemesters', models.IntegerField(default=0)),
                ('livedAbroad', models.BooleanField(default=False)),
                ('livedAbroadDays', models.IntegerField(default=0)),
                ('other', models.BooleanField(default=False)),
                ('otherDescription', models.CharField(blank=True, max_length=255)),
                ('otherDays', models.IntegerField(default=0)),
                ('visionProblems', models.BooleanField()),
                ('visionProblemsDetails', models.TextField(blank=True)),
                ('readingProblems', models.BooleanField()),
                ('readingProblemsDetails', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NativeLangLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nativeLang', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyline',
            name='nativeLanguage1',
        ),
        migrations.RemoveField(
            model_name='surveyline',
            name='nativeLanguage2',
        ),
        migrations.RemoveField(
            model_name='surveyline',
            name='nativeLanguage3',
        ),
        migrations.RemoveField(
            model_name='surveyline',
            name='nativeLanguage4',
        ),
        migrations.AddField(
            model_name='surveyline',
            name='foreignLangBool',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyline',
            name='gender',
            field=models.CharField(choices=[(b'', b''), (b'male', b'Male'), (b'female', b'Female'), (b'other', b'Other')], default='male', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyline',
            name='readingProblems',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyline',
            name='readingProblemsDetails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyline',
            name='visionProblems',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyline',
            name='visionProblemsDetails',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='surveyline',
            name='education',
            field=models.CharField(choices=[(b'', b''), (b'none', 'None'), (b'primary', 'Elementary/Middle School'), (b'secondary', 'High school'), (b'undergrad', 'Undergraduate'), (b'master', 'Master'), (b'phd', 'PhD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyline',
            name='undergradLevel',
            field=models.CharField(blank=True, choices=[(b'', b''), (b'fr', 'Freshman'), (b'sp', 'Sophomore'), (b'jr', 'Junior'), (b'sr', 'Senior')], max_length=50),
        ),
        migrations.AddField(
            model_name='nativelangline',
            name='surveyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyThesis.SurveyLine'),
        ),
        migrations.AddField(
            model_name='foreignlangline',
            name='surveyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyThesis.SurveyLine'),
        ),
    ]
