# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyThesis', '0004_auto_20170903_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignlangline',
            name='worked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foreignlangline',
            name='workedDays',
            field=models.IntegerField(default=0),
        ),
    ]
