# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyThesis', '0006_auto_20170903_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignlangline',
            name='readingProblems',
        ),
        migrations.RemoveField(
            model_name='foreignlangline',
            name='readingProblemsDetails',
        ),
        migrations.RemoveField(
            model_name='foreignlangline',
            name='visionProblems',
        ),
        migrations.RemoveField(
            model_name='foreignlangline',
            name='visionProblemsDetails',
        ),
    ]
