# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyThesis', '0007_auto_20170903_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyline',
            name='participantNumber',
        ),
        migrations.AddField(
            model_name='surveyline',
            name='userName',
            field=models.CharField(default='old', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
