# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveyThesis', '0015_auto_20170905_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeritageLangLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heritageLang', models.CharField(max_length=10)),
                ('explanation', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='surveyline',
            name='gender',
            field=models.CharField(choices=[(b'', b''), (b'male', b'Male'), (b'female', b'Female'), (b'other', b'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='heritagelangline',
            name='surveyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveyThesis.SurveyLine'),
        ),
    ]
