# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyThesis', '0016_auto_20171017_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyline',
            name='heritageLangBool',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
            preserve_default=False,
        ),
    ]
